### ISSUE TITLE
Exporter Directory Structure

### ISSUE THREAD

**Issue by zbindenren** [postfinance/discovery#3]
```
<configured-directory>/servers/<servername>/<namespace>/default/<jobname>.json
<configured-directory>/servers/<servername>/<namespace>/blackbox/<jobname>.json
```

Für prometheus mit namen p1-prom-alsu001.pnet.ch gibt es dann folgende Konfig:

```yaml
scrape_configs:
  - job_name: 'default'
    scrape_interval: 15s
    file_sd_configs:
      - files: ['/appl/prometheus/etc/service-discovery/p1-prom-alsu001.pnet.ch/default/*']
  - job_name: 'k8s_kubelet'
    scrape_interval: 15s
    file_sd_configs:
      - files: ['/appl/prometheus/etc/service-discovery/p1-prom-alsu001.pnet.ch/blackbox/*']
```

Es gibt zwei Registrierungsarten:
* default
* blackbox
